name: seat-booking-containers-stack
services:
  backend-app:
    build: .
    container_name: seat-booking-backend-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/seat_booking_db

  db:
    image: mysql
    container_name: seat-booking-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_DATABASE: seat_booking_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puser1234"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s